---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Demo dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: false
footer: false # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Joyn-Group ServiceDesk Intranet"
  icon: "fas fa-users"
  content: "Joyn Group Servicedesk Intranet"

services:
  - name: "Headquarters"
    icon: "fas fa-building"
    items:
      - name: "Unifi"
        
        icon: "fas fa-wifi"
        subtitle: "Unifi UTM"
        
        url: "https://10.4.0.254/"
      - name: "Paineis Solares"
        
        icon: "fas fa-sun"
        subtitle: "Central de Paineis Solares Huawei"
        
        url: "https://172.16.60.4/"
      - name: "FREEPBX"
        icon: "fas fa-phone"
        
        subtitle: "PBX central telefonica"
        
        url: "http://10.4.1.250"  
      - name: "ISAC"
        icon: "fas fa-fingerprint"
        
        subtitle: "Central biometrica"
        
        url: "http://isac01.infosistema.com"
      - name: "HomeAssistant"
        icon: "fas fa-warehouse"
        
        subtitle: "HomeAssistant"
        
        url: "https://172.16.50.10:8123/"
  - name: "Infraestrutura"
    icon: "fas fa-server"
    items:
      - name: "VCenter"
        #logo: "assets/img/sample.png"
        icon: "fas fa-server"
        subtitle: "VCenter dos hosts VMWare"
        
        url: "https://isvcenter.infosistema.com/login"
        target: "_blank" # optional html a tag target attribute
      - name: "ATA"
        icon: "fas fa-virus"
        
        subtitle: "Microsoft Advanced Threat Analytics"
        
        url: "https://ata.infosistema.com/" 
      - name: "Windows Admin Center"
        icon: "fas fa-user-lock"
        
        subtitle: "Windows Admin Center"
        
        url: "https://lxmap001.infosistema.com:10443/" 
      - name: "Azure"
        icon: "fas fa-cloud"
        
        subtitle: "Microsoft Azure"
        
        url: "https://portal.azure.com/"  

 
  - name: "ServiceDesk"
    icon: "fas fa-headset"
    items:
      - name: "SnipeIT"
        #logo: "assets/img/sample.png"
        icon: "fas fa-desktop"
        subtitle: "Ferramenta de inventario."
        
        url: "https://snipeit.joyn-group.com/login"
        target: "_blank" # optional html a tag target attribute
      - name: "Jira"
        #logo: "assets/img/jira.png"
        icon: "fas fa-ticket-alt"
        subtitle: "Sistema de Tickets"
        
        url: "https://servicedesk.joyn-group.com"
      - name: "TeamPass"
        
        icon: "fas fa-key"
        subtitle: "Password Manager"
        
        url: "https://teampass.infosistema.com"
      - name: "Admin Center"
        icon: "fab fa-windows"
        
        subtitle: "Admin Center da Microsoft" 
        
        url: "https://admin.microsoft.com"
      - name: "Documentação"
        #logo: "assets/img/sample.png"
        icon: "fab fa-google-drive"
        subtitle: "Ferramenta de inventario."
  - name: "Monitoring"
    icon: "fas fa-chart-line"
    items:
      - name: "Zabbix"
        logo: "assets/img/zabbix.png"
        subtitle: "Monitoria de servidores, logs e websites."
        
        url: "https://monitor.joyn-group.com"
        target: "_blank" # optional html a tag target attribute
      - name: "Certificados App"
        #logo: "assets/img/ssl.png"
        icon: "fas fa-lock"
        subtitle: "Monitoria de Certificados SSL e Dominios"
        
        url: "https://monitor.joyn-group.com:8000"

  